# Generated by Django 4.2.30 on 2026-04-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('ecommerce', 'E-commerce'), ('corporativo', 'Corporativo'), ('landing', 'Landing Page'), ('sistema', 'Sistema Web')], max_length=50)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='portafolio/')),
                ('video_demo_url', models.URLField(blank=True, help_text='URL del video demostrativo (YouTube, Vimeo, etc.)')),
                ('demo_url', models.URLField(blank=True, help_text='Link al sitio demo en vivo')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cliente', models.CharField(blank=True, max_length=200)),
                ('resultado', models.CharField(blank=True, help_text='Ej: +200% ventas', max_length=200)),
                ('tiempo_entrega', models.CharField(blank=True, help_text='Ej: 2 semanas', max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición (menor = primero)')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['orden', '-creado'],
            },
        ),
    ]
